<?php

require 'lang_assign.php';

echo "<!--Footer-->";
echo        "<div class='footer-style margint100'>";
echo            "<!--Navigation-->";
echo            "<div class='container paddingt15'>";
//echo                "<script type='text/javascript' src='sectigo_trust_seal.js'></script>";
echo               "<div  class='col-lg-8 offset-lg-2 col-md-10 offset-md-1'>";
echo                    "<div class='row paddingb7'>";
echo                        "<div class='col'>";
echo                            "<a href='edu.php#tentang'>";
echo                                "<h6 class='cl-white'>".$dp['foot_covid']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                        "<div class='col'>";
echo                            "<a href='landing.php#dunia'>";
echo                                "<h6 class='cl-white'>".$dp['foot_wlstatistics']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                    "</div>";
echo                    "<div class='row paddingb7'>";
echo                        "<div class='col'>";
echo                            "<a href='edu.php#pencegahan'>";
echo                                "<h6 class='cl-white'>".$dp['foot_prevention']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                        "<div class='col'>";
echo                            "<a href='article.php'>";
echo                                "<h6 class='cl-white'>".$dp['foot_article']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                    "</div>";
echo                    "<div class='row paddingb7'>";
echo                        "<div class='col'>";
echo                            "<a href='edu.php#gejala'>";
echo                                "<h6 class='cl-white'>".$dp['foot_symptoms']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                        "<div class='col'>";
echo                            "<a href='comment.php'>";
echo                                "<h6 class='cl-white'>".$dp['foot_publiccomment']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                    "</div>";
echo                    "<div class='row paddingb7'>";
echo                        "<div class='col'>";
echo                            "<a href='edu.php#penanganan'>";
echo                                "<h6 class='cl-white'>".$dp['foot_handling']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                        "<div class='col'>";
echo                            "<a href='about.php'>";
echo                                "<h6 class='cl-white'>".$dp['foot_about']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                    "</div>";
echo                    "<div class='row paddingb7'>";
echo                        "<div class='col'>";
echo                            "<a href='landing.php#indonesia'>";
echo                                "<h6 class='cl-white'>".$dp['foot_idstatistics']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                        "<div class='col'>";
echo                            "<a href='copyrightattribute.php'>";
echo                                "<h6 class='cl-white'>".$dp['foot_copyright']."</h6>";
echo                            "</a>";
echo                        "</div>";
echo                    "</div>";
echo                    "<!--Copyright-->";
echo                    "<hr class='hr-footer'>";
echo                    "<div class='font-lato font14-18 cl-white paddingb20'>".$dp['foot_branding']."</div>";
echo                "</div>";
echo            "</div>";
echo        "</div>";
?>
